version: "3.7"

services:
  application:
    build:
      context:  ./
      dockerfile: Dockerfile
    image: mylights
    container_name: mylights
    volumes:
      - type: volume
        source: mylights-db
        target: /mylights/db
      - type: volume
        source: mylights-log
        target: /mylights/logs
    ports:
      - "80:80"
      - "8881:8881"
    restart: on-failure

volumes:
  mylights-db:
  mylights-log: